Update prisma schema
chingu-voyages/v48-tier3-team-24 pull request #39
Opened 2024-03-12 22:01 UTC by Briantam0422

Try my first pull request. I have updated the Prisma schema

1. update model Post
2. add model PostParticipants

2024-03-12 23:28 UTC, mpark4656 approved these changes
Looks good.

2024-03-13 00:41 UTC, ialej001 requested changes
Just a few comments on the schema. Generally, I think we can move away from the boilerplate's `Post` and change all mentions of "post" to "event". Our users won't be creating `Post`s but `Event`s instead, right?

Otherwise, I think this is a great starting point for the application schema! Great job

2024-03-13 00:41 UTC, ialej001 commented on prisma/schema.prisma
>  model Post {
Let's change `Post` to `Event` at all locations in the schema. I believe this is supposed to be the model for an Event so let's make it consistent and appropriate.

2024-03-13 00:41 UTC, ialej001 commented on prisma/schema.prisma
> +    invitLink       String?
typo? misisng an 'e' in `invitLink`

2024-03-13 00:41 UTC, ialej001 commented on prisma/schema.prisma
> +    address         String
I believe we were also going to be allowing users to host virtual events? Wouldn't this along with `lat` and `lng` then be nullable? We can treat null as a virtual event in the front end.

2024-03-13 01:22 UTC, Briantam0422 commented
@ialej001 I think you are right! It makes more sense now. I've updated the code based on your suggestion. Thanks

2024-03-13 02:22 UTC, ialej001 approved these changes

2024-03-13 02:23 UTC, merged