Create My profile page and user update function
chingu-voyages/v48-tier3-team-24 pull request #53
Opened 2024-03-24 23:45 UTC by Briantam0422

**1. My profile page**
<img width="896" alt="image" src="https://github.com/chingu-voyages/v48-tier3-team-24/assets/66020086/7ea95a65-3904-41d7-8ea8-a9004eaa32f3">

**2. handling user update**

**3. Update user password**
<img width="896" alt="image" src="https://github.com/chingu-voyages/v48-tier3-team-24/assets/66020086/a84170e5-d640-40ec-af59-287de154ef62">

**4. Modal component - demo code**
<img width="896" alt="image" src="https://github.com/chingu-voyages/v48-tier3-team-24/assets/66020086/06eb6f62-da5f-4489-a3d7-54a0951635a8">

2024-03-25 02:14 UTC, ialej001 commented
Great work so far, Brian. Is there a way for the user to leave the profile page? Maybe we should add a button on the top right corner (like an X with a circular border) that would reroute the user back to the `/dash` route.

2024-03-25 03:31 UTC, ialej001 requested changes
Great job Brian!

2024-03-30 23:32 UTC, Briantam0422 commented
@ialej001 I have added a back button and changed the label and text you've mentioned. Thanks!

2024-03-31 01:52 UTC, mpark4656 commented on src/server/api/routers/user.ts
> +import toast from "react-hot-toast";
Is this toast import needed in user.ts?

2024-03-31 07:47 UTC, Briantam0422 commented on src/server/api/routers/user.ts
> +import toast from "react-hot-toast";
removed!

2024-03-31 09:40 UTC, Briantam0422 commented
I also added an email update function that allows user to change their email and they need to verify the new email address.
<img width="896" alt="image" src="https://github.com/chingu-voyages/v48-tier3-team-24/assets/66020086/ae88a4d1-9e9e-4954-9d5a-53a0baac514f">
<img width="896" alt="image" src="https://github.com/chingu-voyages/v48-tier3-team-24/assets/66020086/cc6d0c05-009d-4e28-a5cb-5611b00c4e69">
<img width="1544" alt="image" src="https://github.com/chingu-voyages/v48-tier3-team-24/assets/66020086/9b447b32-bbe7-467b-aee6-69a367351940">

2024-03-31 10:23 UTC, ialej001 approved these changes

2024-03-31 15:56 UTC, mpark4656 approved these changes

2024-03-31 15:56 UTC, merged